name: Render and Deploy Bookdown Site

# This triggers the action whenever you push to your main/master branch
on:
  push:
    branches:
      - main # Change to 'master' if that is your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Grant permissions needed for the GITHUB_TOKEN to push to a branch
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup R Environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install R Dependencies and Cache
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rmarkdown
            any::bookdown
            any::knitr
            any::readr

      - name: Build book into _book
        shell: Rscript {0}
        run: |
          bookdown::render_book("index.Rmd", output_dir = "_book")

      - name: Debug output
        run: |
          echo "Contents of _book:"
          ls -la _book

      - name: Deploy _book to website branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: website
          publish_dir: ./_book
