name: Render and Deploy Bookdown Site

on:
  push:
    branches:
      - main

concurrency:
  group: bookdown-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check preinstalled R
        run: R --version

      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          cache-version: 1
          packages: |
            any::rmarkdown
            any::bookdown
            any::knitr
            any::readr

      - name: Build website into _book, knitr
        shell: Rscript {0}
        run: |
          bookdown::render_book("index.Rmd", output_dir = "_book")

      - name: Deploy _book to website branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: website
          publish_dir: ./_book
